server:
  port: 8080

spring:
  application:
    name: product-store
  datasource:
    url: jdbc:postgresql://localhost:5432/product_store?currentSchema=product_store
    username: mac
    password: password
    driver-class-name: org.postgresql.Driver

telegram:
  bot:
    token: 8434445879:AAEpufFtNLzrZul2-koPKuA_xYGJ1cgnFZc
    username: TlyarataStore_bot